#!/usr/bin/env python
# -*- coding: utf-8 -*-
from general import NULL

def dbstr(s): 
	return str(s)

def dbint(i):
	if i in ("", "."):
		return 0
	return int(i)

def dbfloat(i):
	if i in ("", "."):
		return 0.0
	return float(i)

DATABASE_PATH = {
	"item": "./data/item.csv",
	"job": "./data/job.csv",
	"map": "./data/map.csv",
	"monster": "./data/monster.csv",
	"npc": "./data/npc.csv",
	"pet": "./data/pet.csv",
	"shop": "./data/shop.csv",
	"skill": "./data/skill.csv",
}

DATABASE_ROW_MAP_RAW = {
	"item": {
		"#ItemID": (dbint, "item_id"),
		"PictID": (dbint, "pict_id"),
		"IconID": NULL,
		"Item名称": (dbstr, "name"),
		"種別ID": (dbstr, "type"),
		"値段": (dbint, "price"),
		"重量": (dbint, "weight"), #payl
		"容量": (dbint, "capa"),
		"装備時容量": NULL,
		"憑依重量": NULL,
		"修理": NULL,
		"強化ID": NULL,
		"処理フラグ0": NULL,
		"Event": NULL,
		"レシピ可": NULL,
		"染色": NULL,
		"ストック": (dbint, "stock"),
		"両手": NULL,
		"使用時消滅": NULL, 
		"色": NULL,
		"耐久度": (dbint, "durability_max"),
		"装備時変更職業ＩＤ": NULL,
		"初期スロット数": NULL,
		"アイテムチェンジ可否フラグ": NULL,
		"イベントＩＤ": (dbint, "eventid"),
		"エフェクトＩＤ": NULL,
		"発動Skill": NULL,
		"使用可能Skill": NULL,
		"パッシブスキル": NULL,
		"憑依時可能Skill": NULL,
		"憑依パッシブSkill": NULL,
		"ターゲットタイプ": NULL,
		"発動タイプ": NULL,
		"射程": NULL,
		"効果時間": NULL,
		"効果範囲": NULL,
		"効果値": NULL,
		"キャスト": NULL,
		"ディレイ": NULL,
		"HP上昇": (dbint, "hp"),
		"MP上昇": (dbint, "mp"),
		"SP上昇": (dbint, "sp"),
		"最大重量上昇": (dbint, "payl_add"),
		"最大容量上昇": (dbint, "capa_add"),
		"移動力上昇": (dbint, "speed"),
		"STR": (dbint, "str"),
		"MAG": (dbint, "mag"),
		"VIT": (dbint, "vit"),
		"DEX": (dbint, "dex"),
		"AGI": (dbint, "agi"),
		"INT": (dbint, "int"),
		"LUK": (dbint, "luk"),
		"CHA": (dbint, "cha"),
		"物理攻撃力(叩)": (dbint, "atk1"),
		"物理攻撃力(斬)": (dbint, "atk2"),
		"物理攻撃力(突)": (dbint, "atk3"),
		"魔法攻撃力": (dbint, "matk"),
		"物理防御力": (dbint, "DEF"),
		"魔法防御力": (dbint, "mdef"),
		"近命中力": (dbint, "s_hit"),
		"遠命中力": (dbint, "l_hit"),
		"魔法命中力": (dbint, "magic_hit"),
		"近回避力": (dbint, "s_avoid"),
		"遠回避力": (dbint, "l_avoid"),
		"魔回避力": (dbint, "magic_avoid"),
		"クリ力": (dbint, "critical_hit"),
		"クリ回避": (dbint, "critical_avoid"),
		"回復力": (dbint, "heal_hp"),
		"魔法回復力": (dbint, "heal_mp"),
		"無": (dbint, "energy"),
		"火": (dbint, "fire"),
		"水": (dbint, "water"),
		"風": (dbint, "wind"),
		"土": (dbint, "earth"),
		"光": (dbint, "light"),
		"闇": (dbint, "dark"),
		"毒": (dbint, "poison"),
		"石化": (dbint, "stone"),
		"麻痺": (dbint, "paralyze"),
		"睡眠": (dbint, "sleep"),
		"沈黙": (dbint, "silence"),
		"鈍足": (dbint, "slow"),
		"混乱": (dbint, "confuse"),
		"凍結": (dbint, "freeze"),
		"気絶": (dbint, "stan"),
		"人間": NULL,
		"天使": NULL,
		"悪魔": NULL,
		"その他": NULL,
		"男": NULL,
		"女": NULL,
		"LV": NULL,
		"転生": NULL,
		"装備可STR": NULL,
		"装備可MAG": NULL,
		"装備可VIT": NULL,
		"装備可DEX": NULL,
		"装備可AGI": NULL,
		"装備可INT": NULL,
		"装備可LUK": NULL,
		"装備可CHA": NULL,
		"ノービス": NULL,
		"ソードマン": NULL,
		"ブレマス": NULL,
		"バウンテ": NULL,
		"フェンサ": NULL,
		"ナイト": NULL,
		"ダークスト": NULL,
		"スカウト": NULL,
		"アサシン": NULL,
		"コマンド": NULL,
		"アーチャ": NULL,
		"ストライ": NULL,
		"ガンナー": NULL,
		"ウィザ": NULL,
		"ソーサラ": NULL,
		"セージ": NULL,
		"シャーマン": NULL,
		"エレメン": NULL,
		"エンチャン": NULL,
		"ウァテス": NULL,
		"ドルイド": NULL,
		"バード": NULL,
		"ウォーロ": NULL,
		"カバリ": NULL,
		"ネクロマ": NULL,
		"タタラベ": NULL,
		"ブラスミ": NULL,
		"マシンナ": NULL,
		"ファーマ": NULL,
		"アルケミ": NULL,
		"マリオネ": NULL,
		"レンジャ": NULL,
		"エクスプ": NULL,
		"トレジャ": NULL,
		"マーチャ": NULL,
		"トレーダ": NULL,
		"ギャンブラー": NULL,
		"グラディエイター": NULL,
		"ガーディアン": NULL,
		"イレイザー": NULL,
		"ホークアイ": NULL,
		"フォースマスター": NULL,
		"アストラリスト": NULL,
		"カーディナル": NULL,
		"ソウルテイカー": NULL,
		"マエストロ": NULL,
		"ハーヴェスト": NULL,
		"ストライダー": NULL,
		"ロイヤルディーラー": NULL,
		"ジョーカー": NULL,
		"東軍": NULL,
		"西軍": NULL,
		"南軍": NULL,
		"北軍": NULL,
		"所属５": NULL,
		"所属６": NULL,
		"所属７": NULL,
		"所属８": NULL,
		"ブリーダー": NULL,
		"ガーデナー": NULL,
		"フラグ３": NULL,
		"フラグ４": NULL,
		"フラグ５": NULL,
		"フラグ６": NULL,
		"フラグ７": NULL,
		"変身ＩＤ": NULL,
		"封印モンＩＤ": (dbint, "petid"),
		"片手モーションID": (dbint, "s_motion"),
		"両手モーションID": (dbint, "d_motion"),
		"右手憑依者モーション": NULL,
		"左手憑依者モーション": NULL,
		"胸アクセ憑依者モーション": NULL,
		"鎧憑依者モーション": NULL,
		"アイテム欄コメント": NULL,
		"国内ITEM": NULL,
		"国内ITEM2": NULL,
		"検索フラグ": NULL,
		"ワールド用リサイクルポイント": NULL,
	},
	"job": {
		"#job_id": (dbint, "job_id"),
		"job_name": (dbstr, "name"),
		"hp_rate": (dbfloat, "hp_rate"),
		"mp_rate": (dbfloat, "mp_rate"),
		"sp_rate": (dbfloat, "sp_rate"),
		"payl_rate": (dbfloat, "payl_rate"),
		"capa_rate": (dbfloat, "capa_rate"),
	},
	"map": {
		"#マップＩＤ": (dbint, "map_id"),
		"マップ名": (dbstr, "name"),
		"中心座標ｘ": (dbfloat, "centerx"),
		"中心座標ｙ": (dbfloat, "centery"),
	},
	"monster": {
		"##": (dbint, "monster_id"),
		"体格": NULL,
		"特殊情報": NULL,
		"設定": NULL,
		"基本パラメータ": NULL,
		"ステータス": NULL,
		"物理攻撃": NULL,
		"魔法攻撃": NULL,
		"防御力": NULL,
		"命中": NULL,
		"回避": NULL,
		"クリティカル": NULL,
		"攻撃速度": NULL,
		"属性値": NULL,
		"状態異常耐性": NULL,
		"思考ID(通常）": NULL,
		"思考(出現)": NULL,
		"思考ID(瀕死)": NULL,
		"思考(終焉）": NULL,
		"スキルリスト": NULL,
		"↓減少HP%分加算": NULL,
		"↓減少HP%分減算": NULL,
		"↓ボス召喚時のスキル": NULL,
		"↓最初最後使用するスキル": NULL,
		"経験値": NULL,
		"ドロップ": NULL,
		"ドロップアイテム": NULL,
		"旅人のメモ": NULL,
		"パーティ": NULL,
	},
	"npc": {
		"#NPCID": (dbint, "npc_id"),
		"NAME": (dbstr, "name"),
		"MAPID": NULL,
		"座標Ｘ": NULL,
		"座標Ｙ": NULL,
		"方向": NULL,
		"scale": NULL,
		"EVENTID": NULL,
		"NOTOUCH": NULL,
		"ＰＩＣＴＩＤ": NULL,
		"初期モーション": NULL,
		"透明度(0~255)この値を 0 以外にすると重くなるので注意してください": NULL,
		"デフォルト表示": NULL,
		"円形影の描画": NULL,
		"FLAG": NULL,
		"NPC表示設定": NULL,
	},
	"pet": {
		"#PETID": (dbint, "pet_id"),
		"ペット名（ペット名は10文字まで）": (dbstr, "name"),
		"PICTID": (dbint, "pict_id"),
		"種別ID": NULL,
		"体の幅": NULL,
		"体の長さ": NULL,
		"スケール": NULL,
		"特殊情報": NULL,
		"基本パラメータ": NULL,
		"戦闘パラメータ": NULL,
		"属性値": NULL,
		"状態異常耐性": NULL,
		"思考ID(通常時）": NULL,
		"思考ID(出現時)": NULL,
		"思考ID(瀕死時)": NULL,
		"思考ID(終焉時）": NULL,
		"スキルリスト": NULL,
		"EXP": NULL,
		"JOBEXP": NULL,
		"ドロップアイテム": NULL,
		"ドロップアイテム": NULL,
		"騎乗者非表示設定": NULL,
		"備考": NULL,
	},
	"shop": {
		"#ショップID": (dbint, "shop_id"),
		"商品ID1": (dbint, 1),
		"商品ID2": (dbint, 2),
		"商品ID3": (dbint, 3),
		"商品ID4": (dbint, 4),
		"商品ID5": (dbint, 5),
		"商品ID6": (dbint, 6),
		"商品ID7": (dbint, 7),
		"商品ID8": (dbint, 8),
		"商品ID9": (dbint, 9),
		"商品ID10": (dbint, 10),
		"商品ID11": (dbint, 11),
		"商品ID12": (dbint, 12),
		"商品ID13": (dbint, 13),
	},
	"skill": {
		'"ID"': (dbint, "skill_id"),
		'"Name"': (dbstr, "name"),
		'"説明"': NULL,
		'"Active"': NULL,
		'"MaxLv"': (dbint, "maxlv"),
		'"Lv"': NULL,
		'"MP"': NULL,
		'"SP"': NULL,
		'"HP"': NULL,
		'"射程"': NULL,
		'"ターゲット"': NULL,
		'"ターゲット2"': NULL,
		'"範囲"': NULL,
		'"適応"': NULL,
		'"Zero"': NULL,
		'"Flag"': NULL,
		'"?"': NULL,
		'"nTarget2"': NULL,
		'"射程"': NULL,
		'"0"': NULL,
		'"MarkTarget"': NULL,
		'"MarkTarget"': NULL,
		'"MarkCaster"': NULL,
		'"icon"': NULL,
		'"MarkTarget"': NULL,
		'"0"': NULL,
		'"mark?"': NULL,
		'"MarkRound"': NULL,
		'"MarknewObj"': NULL,
		'"AnimStart"': NULL,
		'"AnimLoop"': NULL,
		'"AnimAttack"': NULL,
	},
}

DATABASE_ROW_MAP_EXT = {
	"item": {
		#3: (dbstr, "name"),
	},
	"job": {},
	"map": {},
	"monster": {
		1: (dbstr, "name"),
	},
	"npc": {},
	"pet": {
		19: (dbint, "maxhp"),
	},
	"shop": {},
	"skill": {},
}